spring.application.name=CaribePay

# MongoDB (Spring Data)
spring.mongodb.uri=${DB_URL:mongodb://localhost:27017/caribepay}

# JWT
jwt.secret=${JWT_SECRET:MiClaveSecretaMuyLargaParaCaribePay123456789}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Server
server.port=8080

# Logging
logging.level.root=INFO